name: limnopapers
channels:
- conda-forge
dependencies:
        - pandas
        - python-twitter
        - feedparser
        - colorama
        - argcomplete
        - pytest
        - black
        - mastodon.py
