---
title: "limnopapers"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    self_contained: TRUE
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(DT)
library(dplyr)
library(stringr)
```


```{r, echo=FALSE, out.width="100%", warning=FALSE}
dt <- read.csv("dashboard.csv")
dt <- dplyr::select(dt, title, source = dc_source, url = prism_url)

# dt$date <- strptime(as.POSIXct(dt$date), format = "%Y-%m-%d")
# dt$date <- format(dt$date, "%Y-%m-%d")

create_link <- function(x) {
  # x <- dt$url[1]
  if (is.na(x)) {
    return("")
  } else {
    sprintf(paste0('<a href="', URLdecode(x), '" target="_blank">', substr(x, 1, 25), "</a>"))
  }
}

dt$url <- lapply(dt$url, function(x) sapply(x, create_link))

dt_table <- DT::datatable(dt,
  options = list(
    scrollX = TRUE,
    autoWidth = TRUE,
    columnDefs = list(
      list(width = "30%", targets = c(3)))
  ),
  rownames = FALSE,
  fillContainer = TRUE,
  width = "100%",
  colnames = c("Title", "Source", "URL"))

dt_table <- formatStyle(dt_table, columns = 1:4, fontSize = "80%")
dt_table <- formatStyle(dt_table, columns = 1, width = "500px")

dt_table
```
