name: pytest

on: 
  push:
    paths:
      - 'requirements.txt'
      - 'tests/**'
      - 'limopapers/**'
      - 'bin/**'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Setup config
      run: |
        echo '${{ secrets.ACCESS_TOKEN_KEY }}' >> config.py
        echo '${{ secrets.ACCESS_TOKEN_SECRET }}' >> config.py
        echo '${{ secrets.CONSUMER_KEY }}' >> config.py
        echo '${{ secrets.CONSUMER_SECRET }}' >> config.py
        echo '${{ secrets.MASTODON_TOKEN }}' >> limnopapers_clientcred.secret
        echo 'https://fediscience.org' >> limnopapers_clientcred.secret
    - name: Install package
      run: |
        pip install -e .
    - name: Test with pytest
      run: |
        pytest -v --ignore=scratch --ignore=build_dashboard.py
        