name: run

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 15 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip        
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Setup config
      run: |
        echo '${{ secrets.ACCESS_TOKEN_KEY }}' >> config.py
        echo '${{ secrets.ACCESS_TOKEN_SECRET }}' >> config.py
        echo '${{ secrets.CONSUMER_KEY }}' >> config.py
        echo '${{ secrets.CONSUMER_SECRET }}' >> config.py
        echo '${{ secrets.MASTODON_TOKEN }}' >> limnopapers_clientcred.secret
        echo 'https://fediscience.org' >> limnopapers_clientcred.secret
    - name: Install package
      run: |
        pip install -e .    
    - name: Run
      run: |
        limnopapers --tweet
    - name: Commit and push if changed
      run: |-
        git diff
        git config --global user.email "limnopapers-bot@example.com"
        git config --global user.name "limnopapers-bot"
        git add log.csv
        git commit -m "Updated log" || exit 0
        git push
